version: 0.2

phases:
  install:
    commands:
      - wget "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip "terraform_${TF_VERSION}_linux_amd64.zip" -d /usr/bin
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version

  pre_build:
    commands:
      - cd terraform/example
      - terraform init
      - terraform plan

  # build:
  #   commands:
  #     - terraform apply -auto-approve
